param([int]$CdpPort=9275,[string]$OutputDirectory='')
$ErrorActionPreference='Stop'
if(-not $OutputDirectory){$OutputDirectory=Join-Path (Split-Path -Parent $PSScriptRoot) 'outputs\integration-final-runtime'}
New-Item -ItemType Directory -Force -Path $OutputDirectory|Out-Null
$id=0;$socket=$null
function OpenPage([string]$role){if($script:socket){$script:socket.Dispose()};$pages=Invoke-RestMethod "http://127.0.0.1:$CdpPort/json/list";$p=@($pages|Where-Object{$_.type-eq'page'-and $_.url-match "[?&]window=$role"})[0];if(-not $p){throw "missing $role"};$script:socket=[Net.WebSockets.ClientWebSocket]::new();$script:socket.ConnectAsync([uri]$p.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult()}
function Call([string]$method,[hashtable]$params=@{}){$script:id++;$want=$script:id;$raw=@{id=$want;method=$method;params=$params}|ConvertTo-Json -Depth 20 -Compress;$bytes=[Text.Encoding]::UTF8.GetBytes($raw);$script:socket.SendAsync([ArraySegment[byte]]::new($bytes),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult();do{$ms=[IO.MemoryStream]::new();do{$buf=New-Object byte[] 65536;$r=$script:socket.ReceiveAsync([ArraySegment[byte]]::new($buf),[Threading.CancellationToken]::None).GetAwaiter().GetResult();$ms.Write($buf,0,$r.Count)}while(-not $r.EndOfMessage);$msg=[Text.Encoding]::UTF8.GetString($ms.ToArray())|ConvertFrom-Json}while($msg.id-ne$want);$msg}
function Eval([string]$expr,[bool]$await=$false){$r=Call 'Runtime.evaluate' @{expression=$expr;returnByValue=$true;awaitPromise=$await};if($r.result.exceptionDetails){throw ($r.result.exceptionDetails|ConvertTo-Json -Compress)};$r.result.result.value}
function Shot([string]$name){$r=Call 'Page.captureScreenshot' @{format='png'};$p=Join-Path $OutputDirectory $name;[IO.File]::WriteAllBytes($p,[Convert]::FromBase64String($r.result.data));$p}
$out=[ordered]@{generatedAt=(Get-Date).ToString('o');roles=$null;presentation=$null;expressions=@();motion=$null;watermark=$null;screenshots=@()}
OpenPage settings
$out.roles=Eval @'
(async()=>{const s=await window.starchat.state.get(),base=s.role;const blank={...base,id:'role.integration.blank',displayName:'验收空白角色',identity:{...base.identity,name:'空白验收'},personality:{...base.personality,systemPrompt:'SYSTEM SNAPSHOT BLANK ROLE'}};const copy={...base,id:'role.integration.copy',displayName:'验收复制角色',personality:{...base.personality,systemPrompt:'SYSTEM SNAPSHOT COPY ROLE'}};await window.starchat.roles.save({role:blank});await window.starchat.roles.save({role:copy});const a=await window.starchat.roles.activate({id:blank.id});const snapA={id:a.role.id,prompt:a.role.personality.systemPrompt,hasApiKey:a.hasApiKey};const b=await window.starchat.roles.activate({id:copy.id});const snapB={id:b.role.id,prompt:b.role.personality.systemPrompt,hasApiKey:b.hasApiKey};let protectedDefault=false;try{await window.starchat.roles.delete({id:'baoyin.default'})}catch{protectedDefault=true}const final=await window.starchat.state.get();return {blankId:blank.id,copyId:copy.id,independent:blank.id!==copy.id,snapA,snapB,snapshotChanged:snapA.prompt!==snapB.prompt,roles:final.roles.map(r=>r.id),active:final.role.id,protectedDefault,keyExcluded:!JSON.stringify([blank,copy]).toLowerCase().includes('apikey')}})()
'@ $true
$out.presentation=Eval @'
(async()=>{const before=await window.starchat.debug.metrics();window.starchat.settings.preview({domain:'presentation',patch:{bodyFollowStrength:.77,bodyLag:.44,inertiaStrength:.31,idleSwayStrength:.08,physicsEnabled:false}});await new Promise(r=>setTimeout(r,500));const off=await window.starchat.debug.metrics();await window.starchat.settings.save({settings:{presentation:{bodyFollowStrength:.77,bodyLag:.44,inertiaStrength:.31,idleSwayStrength:.08,physicsEnabled:true}}});await new Promise(r=>setTimeout(r,500));const on=await window.starchat.debug.metrics();const state=await window.starchat.state.get();return {beforePhysics:before?.physicsEnabled,previewPhysics:off?.physicsEnabled,persistedPhysics:on?.physicsEnabled,stored:state.settings.presentation}})()
'@ $true
OpenPage pet
$moduleUrl=Eval "performance.getEntriesByType('resource').map(x=>x.name).find(x=>x.includes('live2d-runtime-'))||new URL('./assets/live2d-runtime-C4jd12j9.js',location.href).href"
if(-not $moduleUrl){throw 'runtime module URL missing'}
[void](Eval "import('$moduleUrl').then(m=>{m.clearCubismTimeline?.();return true})" $true)
$names=@('blush','confused','cry','lean_forward','sing','heart','leek_prop')
foreach($name in $names){OpenPage pet;[void](Eval "import('$moduleUrl').then(m=>{m.controller.playExpression('$name');return true})" $true);Start-Sleep -Milliseconds 350;$before=Eval "import('$moduleUrl').then(m=>JSON.stringify({metrics:m.getCubismMetrics(),timeline:m.getCubismTimeline().slice(-8)}))" $true|ConvertFrom-Json;$shot=Shot "expression-$name.png";$out.screenshots+=$shot;$out.expressions+=[ordered]@{name=$name;metrics=$before.metrics;timeline=$before.timeline;screenshot=$shot}}
OpenPage settings;[void](Eval "window.starchat.presentation.emit({type:'control',name:'neutral',source:'system',layer:'manual'});window.starchat.presentation.emit({type:'action',name:'greet',source:'system',layer:'manual'});true");Start-Sleep -Milliseconds 250;OpenPage pet;$m1=Eval "import('$moduleUrl').then(m=>JSON.stringify(m.getCubismMetrics()))" $true|ConvertFrom-Json;Start-Sleep -Seconds 4;$m2=Eval "import('$moduleUrl').then(m=>JSON.stringify(m.getCubismMetrics()))" $true|ConvertFrom-Json;$out.motion=[ordered]@{started=$m1.activeMotion;ended=$m2.activeMotion;expressionAfter=$m2.activeExpression;timeline=Eval "import('$moduleUrl').then(m=>JSON.stringify(m.getCubismTimeline().slice(-30)))" $true|ConvertFrom-Json}
OpenPage settings;[void](Eval "window.starchat.settings.save({settings:{live2dShowWatermark:false}}).then(()=>true)" $true);Start-Sleep -Milliseconds 600;OpenPage pet;$off=Eval "import('$moduleUrl').then(m=>JSON.stringify(m.getCubismMetrics()))" $true|ConvertFrom-Json;$offShot=Shot 'watermark-off.png';OpenPage settings;[void](Eval "window.starchat.settings.save({settings:{live2dShowWatermark:true}}).then(()=>true)" $true);Start-Sleep -Milliseconds 600;OpenPage pet;$on=Eval "import('$moduleUrl').then(m=>JSON.stringify(m.getCubismMetrics()))" $true|ConvertFrom-Json;$onShot=Shot 'watermark-on.png';OpenPage settings;[void](Eval "window.starchat.settings.save({settings:{live2dShowWatermark:false}}).then(()=>true)" $true);Start-Sleep -Milliseconds 600;OpenPage pet;$finalOff=Eval "import('$moduleUrl').then(m=>JSON.stringify(m.getCubismMetrics()))" $true|ConvertFrom-Json;$out.screenshots+=@($offShot,$onShot);$out.watermark=[ordered]@{offValue=$off.watermarkParameterValue;onValue=$on.watermarkParameterValue;finalValue=$finalOff.watermarkParameterValue;offScreenshot=$offShot;onScreenshot=$onShot;nativeLayer=$off.overlayOrder}
$socket.Dispose();$out|ConvertTo-Json -Depth 40|Set-Content (Join-Path $OutputDirectory 'integration-final-runtime.json') -Encoding utf8;$out|ConvertTo-Json -Depth 8
